import Link from "next/link";
import "../styles/globals.css";
import Image from "next/image";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const header = (
    <header>
      <link rel="icon" href="/star-fill.svg" />
      <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
        <Image src="/logo.png" width={40} height={40} className="mx-auto" />
        <Link href = '/'>
          <h1 className="font-blod text-white text-3xl">IngGu's Blog</h1>
        </Link>
        <p className="text-slate-300">Welcome to my blog.</p>
        <br />
      </div>
    </header>
  );
  
  const footer = (
    <footer>
      <div className="border-t border-slate-400 mt-6 py-6 text-center text-slate-400"> 
        <h3>Developed by IngGu</h3>
      </div>
    </footer>
  );

  return (
    <html lang="ko">
      <body>
        <div className="mx-auto max-w-2xl px-6">
        {header}
        {children}
        {footer}
        </div>
        </body>
    </html>
  )
}
